### ISSUE TITLE
Images rotate automatically

### ISSUE THREAD

**Issue by mvalbuquerque** [ZacharyKhan/ZKCarousel#1]
Hello!
Is there any property that causes the image to rotate automatically without the user touching the screen?

Tks,

**Comment by ZacharyKhan** [comment]
Hey there @mvalbuquerque , currently there is not. I can work on this tonight and add this functionality to auto traverse through the carousel items.

**Comment by elmz87** [comment]
@ZacharyKhan would love to see this feature too!

**Comment by ZacharyKhan** [comment]
Sorry guys, I’ve been crammed with school and work. I’ll get to this as soon as possible!

**Comment by ZacharyKhan** [comment]
Added in PR #4 👍 

run `pod update` and make sure you are using pod 0.1.3 to use the feature. I will update the README with documentation shortly.

**Comment by mvalbuquerque** [comment]
Thank you very much for the response and look forward to the new version. Could you notify me, please? God bless.


> Em 4 de jan de 2018, à(s) 21:50, Zachary Khan <notifications@github.com> escreveu:
> 
> Hey there @mvalbuquerque <https://github.com/mvalbuquerque> , currently there is not. I can work on this tonight and add this functionality to auto traverse through the carousel items.

**Comment by ZacharyKhan** [comment]
What do you mean notify you? Im confused.
