### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by mahi008** [ZacharyKhan/ZKCarousel#15]
Hello,
   First of all thank you for this useful lib. and Is there any chance of getting an updated version
for swift 4 ?, because I tried to import the actual version. It throws some errors, even though I can correct those by Xcode suggested remplacements. I prefer getting an official updated version :)

Thankyou.

**Comment by ZacharyKhan** [comment]
Hey @mahi008, if anyone else is interested in giving it a shot and submitting a PR with the Swift 4 fixes  feel free! I may have some time this weekend to do it if nobody else has.

**Comment by mahi008** [comment]
Hey @ZacharyKhan Great 🙏, once again thanks for this lib.

**Comment by ZacharyKhan** [comment]
Give it a try now, should be fixed in #16 👍

**Comment by mahi008** [comment]
works great ! one last question though, nothing to do with the issue but how can I add equal margins around the ZKCarousel? It looks nearly impossible, I have tried UIEdgeInsets on collection view but nothing helps :(

**Comment by ZacharyKhan** [comment]
>works great ! one last question though @ZacharyKhan , nothing to do with the issue but how can I add equal margins around the ZKCarousel? It looks nearly impossible, I have tried UIEdgeInsets on collection view but nothing helps :(

@mahi008 I’m confused, which views exactly are you trying to add margins in between?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mahi008** [comment]
[Here's](https://cdn1.imggmi.com/uploads/2018/9/29/9687e3b719446026856798578aa9e6b0-full.png) my story board, the blue rectangle is my ZKCarousel and it is embeded in a tableHeaderView.
I want to add white space around the blue rectangle(my carousel) but I can't figure it out :(

**Comment by ZacharyKhan** [comment]
@mahi008 Are you adding `ZKCarousel` programatically or with storyboards? This seems like it could be solved by adding constraints to the top/left/bottom/right of the `ZKCarousel` and adding a margin that way. 

You shouldn't set the `UIEdgeInsets` on `ZKCarousel`.
