### ISSUE TITLE
Can we add tap gesture recognizer?

### ISSUE THREAD

**Issue by elmz87** [ZacharyKhan/ZKCarousel#2]

**Comment by ZacharyKhan** [comment]
Yes, absolutely.

I'm guessing you want to be able to tap the carousel and have it go to the next slide? If you could elaborate a bit more on what exactly the gesture recognizer should do that would be awesome!

**Comment by ZacharyKhan** [comment]
Added in PR #3. Update your pod file to 0.1.2 👍
