### ISSUE TITLE
Is it possible to turn of the dark gradient on the slides?

### ISSUE THREAD

**Issue by ChrisAldridgeRIT** [ZacharyKhan/ZKCarousel#22]
I'm not showing the title or description on the slide so would prefer not to have the dark gradient on the slides if possible.

**Comment by ZacharyKhan** [comment]
I don't think so, not at the moment. If I get some time in the next couple of days I will implement this functionality. You're welcome to fork the repo and submit a PR with your own implementation for the time-being.

**Comment by ZacharyKhan** [comment]
Your best bet is to go into the `ZKCarousel.swift` file in your project and do the following:

``` swift
// 1) Find the carouselCollectionViewCell class

fileprivate class carouselCollectionViewCell: UICollectionViewCell {
}

// 2) Within the carouselCollectionViewCell class, you will see the following computed property

private lazy var imageView : UIImageView = {
        let iv = UIImageView()
        iv.contentMode = .scaleAspectFill
        iv.backgroundColor = .clear
        iv.clipsToBounds = true
        iv.addBlackGradientLayer(frame: self.bounds)
        iv.translatesAutoresizingMaskIntoConstraints = false
        return iv
}()

// 3) REMOVE this from the computed property

iv.addBlackGradientLayer(frame: self.bounds)
```

For the time-being, this should solve your problem and remove the gradient. The best option is for me to open up `ZKCarousel` to allow developers to use any `UICollectionViewCell` within `ZKCarousel`. If no cell is provided, it will default to the currently provided cell.
