### ISSUE TITLE
Adding tap gesture not working 

### ISSUE THREAD

**Issue by hamza-mansouur** [ZacharyKhan/ZKCarousel#25]
Hello ! I want to add a tap gesture to go to a giving URL of the selected slide but when i add a tap gesture to the carousel view it doesn't work.

**Comment by ZacharyKhan** [comment]
Can you post your code? I need to see how you are using the gesture recognizer and what exactly you are trying to achieve. Thanks!

**Comment by ZacharyKhan** [comment]
@hamza-mansouur have you figured out the solution to your problem? I will close this issue due to inactivity. Please open another issue and post a code snippet if you are still having issues with ZKCarousel.
