### ISSUE TITLE
Facing cell reusable issue in Collection view

### ISSUE THREAD

**Issue by AB91189** [ZacharyKhan/ZKCarousel#33]
HI,

I am using the ZKCarousel in a collection view. I am dequeresuing a collection view cell. The images are getting set from a URL array. if I scroll the collection view (fast) and the images are still downloading, the new collection view cell carousel is holding the image of the previous cell which is already loaded, and when the download completes it resets. I want to keep it blank till the image is downloading. Can you please suggest anything.  Really really need help.

Thanks

**Comment by ZacharyKhan** [comment]
Hello @AB91189, 

This is a common problem people have with UICollectionViews when asynchronously loading data (commonly images). There are a couple of things that you should note:

- ZKCarousel _is_ a UICollectionView. More specifically, it's a UIView with a UICollectionView encapsulated inside of it. 

- ZKCarousel does not have out-of-the-box support for loading images asynchronously, but this can be easily implemented using a library such as **SDWebImage**. 

For me to help you with code, I would need to see your codebase to understand things like the state of your data and how you are managing the UI. What I can do is abstract the UICollectionViewCell class away from ZKCarousel which would allow you to create a custom UICollectionViewCell and subclass the ZKCarouselCell (which I will create). Once you have done that, you can add your own view to the cell and either 1) manage the state of the image yourself to show as blank until loaded, or 2) use a library such as SDWebImage to do the heavy lifting for you. 

I can make the updates to this library shortly and will update you once this is done.
