### ISSUE TITLE
Make UIImageView from ZKCarouselCell public

### ISSUE THREAD

**Issue by alezoffoli** [ZacharyKhan/ZKCarousel#39]
I was thinking on having access to the `imageView` to edit some of its properties. Specifically, I currently want to be able to change the `contentMode` to `.scaleAspectFit`. But more customization might be cool for the future.

We can make `imageView` public, or could also consider having some public methods to allow editing of some specific properties, but making the property public seems more flexible. What do you think?

**Comment by ZacharyKhan** [comment]
This seems like a reasonable ask 😄 if you'd like to open a PR with these changes I'm happy to push them through and send out a new release.

**Comment by alezoffoli** [comment]
Hmm I've analyzed a little bit more here. As the ZKCarouselCell is entirely handled by ZKCarousel, it wouldn't be so trivial. It's possible, but we would have to pass the properties when creating a ZKCarouselSlide. I will implement this in my fork for now and contribute if I think this becomes an interesting thing for other users as well

Thanks!
