### ISSUE TITLE
How can get selected index ?

### ISSUE THREAD

**Issue by afiq90** [ZacharyKhan/ZKCarousel#5]
Hey guys, how can I get selected index for ZKCarousel? Thanks in advance.

**Comment by ZacharyKhan** [comment]
I can add a function to return the selected index. Give me 30 minutes 👍

**Comment by afiq90** [comment]
Okay, thanks

**Comment by ZacharyKhan** [comment]
run `pod update` and make sure you're on version 0.1.4, I've added the following function to return the selectedIndexPath: 

```swift
carousel.selectedIndexPath()
```

**Comment by afiq90** [comment]
Thank you

**Comment by Spettacolo83** [comment]
Is it possible to receive a callback when the scroll has been executed (manual and automatic)?
Thanks!

**Comment by magichim** [comment]
@ZacharyKhan I want same feature that @Spettacolo83 comment. 

When I slide it, get a index or other logic is executed.

Could you make it?

**Comment by ZacharyKhan** [comment]
> @ZacharyKhan I want same feature that @Spettacolo83 comment. 
> 
> 
> 
> When I slide it, get a index or other logic is executed.
> 
> 
> 
> Could you make it?


@magichim I will take a look this evening and see if I can implement this for you.
