### ISSUE TITLE
Autolayout issues with iphone8 and iphone8plus

### ISSUE THREAD

**Issue by elmz87** [ZacharyKhan/ZKCarousel#7]
Hi it seems i have a problem to set the carousel
self.carouselImageArr.frame = self.carousel.frame

When i load in iPhone8 it looks fine,
however when i load in iPhone8 Plus the carousel does not fill the view.

**Comment by ZacharyKhan** [comment]
@elmz87 I would suggest using auto layout and `NSLayoutConstraints` rather than setting the frame. 

Would you mind posting a code snippet here?

**Comment by ZacharyKhan** [comment]
I've updated the carousel to use NSLayout constraints manually rather than using a visual format. Run `pod update` and make sure you're on version `0.1.5` and let me know if the issue persists or if it's solved with this release.

**Comment by ZacharyKhan** [comment]
Closing, this should have been fixed in latest release. If the issue persists, please re-open this issue or create a new one.
