### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by snake302** [ZacharyKhan/ZKCarousel#8]
I have added constraints to my view, but still receiving this issue. Is there any way to use it without constrains?

`2018-01-29 13:55:44.126069+0300 ARMPanel[40948:3156916] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x604000282a80 h=--& v=--& ZKCarousel.ZKCarousel:0x7ffbd1f1bfd0.width == 0   (active)>",
    "<NSLayoutConstraint:0x60000009e550 H:|-(20)-[UIPageControl:0x7ffbd1f1cfa0]   (active, names: '|':ZKCarousel.ZKCarousel:0x7ffbd1f1bfd0 )>",
    "<NSLayoutConstraint:0x60000009e5a0 H:[UIPageControl:0x7ffbd1f1cfa0]-(20)-|   (active, names: '|':ZKCarousel.ZKCarousel:0x7ffbd1f1bfd0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000009e5a0 H:[UIPageControl:0x7ffbd1f1cfa0]-(20)-|   (active, names: '|':ZKCarousel.ZKCarousel:0x7ffbd1f1bfd0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2018-01-29 13:55:44.139670+0300 ARMPanel[40948:3156916] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600000281f40 H:|-(15)-[UILabel:0x7ffbd1d212f0'lorem ipsum devornum cora...'](LTR)   (active, names: '|':_TtC10ZKCarouselP33_624CA1E1E5D572C4565286BDA098607126carouselCollectionViewCell:0x7ffbd1e1eac0 )>",
    "<NSLayoutConstraint:0x600000281f90 UILabel:0x7ffbd1d212f0'lorem ipsum devornum cora...'.right == _TtC10ZKCarouselP33_624CA1E1E5D572C4565286BDA098607126carouselCollectionViewCell:0x7ffbd1e1eac0.right - 15   (active)>",
    "<NSLayoutConstraint:0x604000283520 'UIView-Encapsulated-Layout-Width' _TtC10ZKCarouselP33_624CA1E1E5D572C4565286BDA098607126carouselCollectionViewCell:0x7ffbd1e1eac0.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600000281f90 UILabel:0x7ffbd1d212f0'lorem ipsum devornum cora...'.right == _TtC10ZKCarouselP33_624CA1E1E5D572C4565286BDA098607126carouselCollectionViewCell:0x7ffbd1e1eac0.right - 15   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2018-01-29 13:55:44.140534+0300 ARMPanel[40948:3156916] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600000282170 H:|-(15)-[UILabel:0x7ffbd1e1ed40'A Demo Slide \U261d\Ud83c\Udffc']   (active, names: '|':_TtC10ZKCarouselP33_624CA1E1E5D572C4565286BDA098607126carouselCollectionViewCell:0x7ffbd1e1eac0 )>",
    "<NSLayoutConstraint:0x6000002821c0 H:[UILabel:0x7ffbd1e1ed40'A Demo Slide \U261d\Ud83c\Udffc']-(15)-|   (active, names: '|':_TtC10ZKCarouselP33_624CA1E1E5D572C4565286BDA098607126carouselCollectionViewCell:0x7ffbd1e1eac0 )>",
    "<NSLayoutConstraint:0x604000283520 'UIView-Encapsulated-Layout-Width' _TtC10ZKCarouselP33_624CA1E1E5D572C4565286BDA098607126carouselCollectionViewCell:0x7ffbd1e1eac0.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000002821c0 H:[UILabel:0x7ffbd1e1ed40'A Demo Slide ☝🏼']-(15)-|   (active, names: '|':_TtC10ZKCarouselP33_624CA1E1E5D572C4565286BDA098607126carouselCollectionViewCell:0x7ffbd1e1eac0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
`

**Comment by ZacharyKhan** [comment]
I've updated the carousel to use NSLayout constraints manually rather than using a visual format. Run pod update and make sure you're on version 0.1.5 and let me know if the issue persists or if it's solved with this release.

Since ZKCarousel is a subclass of `UIView`, you can add it to any UIView as a subview of that view and layout either with constraints or by manually setting the `frame` property of ZKCarousel.

If you're using a `Main.storyboard` make sure you're setting the constraints properly via the visual editor.  

See example demo for a better idea.

**Comment by snake302** [comment]
Huge thanks! Solved by setting frame property 👍
